name: Secret Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "CI running"
      - run: echo "Secret is ${{ secrets.MEOW }}"
      
      - uses: actions/checkout@v4
      - run: ./build.sh
        env:
          MEOW: ${{ secrets.MEOW }}
